### ISSUE TITLE
HEOS account password

### ISSUE THREAD

**Issue by marktheknife** [dcmeglio/hubitat-heos#3]
Hey there @dcmeglio, I tried logging into my HEOS account from the hubitat app and it’s giving me a login incorrect error, but I’m pretty sure the password is right. I can always try resetting my HEOS password, but before I do that, any other suggestions? Thanks!

**Comment by marktheknife** [comment]
Here’s what the debug log looks like when I try to login.

![B4BC5639-ABD7-426E-90B9-5AFD4C732CDD](https://user-images.githubusercontent.com/16859844/73153671-838d6380-4089-11ea-980c-e250ff88a157.jpeg)

**Comment by dcmeglio** [comment]
Does your password have any special characters? Especially a space & = % or ?

**Comment by marktheknife** [comment]
Yeah that could be it, there’s a & and a * in there. When I get home I’ll change it and try again. Thanks!

**Comment by dcmeglio** [comment]
I suspect the & is the problem. I would need to modify the code to escape it. To test my theory in your password replace the & with %26 and tell me if that works. That will prove my theory then I can actually fix it.

**Comment by marktheknife** [comment]
That worked! The app is discovering speakers now!!

**Comment by dcmeglio** [comment]
This issue should now be fixed which means you'll want to change the %26 back to an & it will now be automatically escaped by the integration.
