### ISSUE TITLE
HEOS speaker not discovered

### ISSUE THREAD

**Issue by marktheknife** [dcmeglio/hubitat-heos#4]
So now that I've got the password issue sorted out, I went on to device discovery. My Marantz AVR is found immediately (connected via ethernet), but my HEOS 3 Wifi speaker isn't discovered at all. I've tried re-running discovery a few times. Here's some of the log output, you can see where the HEOS speaker that does connect gives a report back, which  includes the other speaker that the app can't seem to find.

![image](https://user-images.githubusercontent.com/16859844/73232683-037f0080-4152-11ea-98b5-219c017ff9a5.png)

Appreciate any thoughts/suggestions.

**Comment by dcmeglio** [comment]
The app uses ssdp to discover devices. I used to have a lot of trouble with that with my heos but it’s been fine lately. Do you have the latest heos app and are the devices on the latest firmware?

**Comment by marktheknife** [comment]
Yup, latest app version and device firmware.

**Comment by dcmeglio** [comment]
Hmm. Does the heos app detect them quickly if you go to my devices? Is you hubitat, which is wired, on the same up subnet as the heos? Ssdp won’t span subnets. For example if your wired stuff is 192.168.1.x and wireless is 192.168.86.x (what google wifi does) that would cause this. I can come up with a workaround but it’d be good to know if that’s the issue.

**Comment by marktheknife** [comment]
Now that you mention it, the HEOS app intermittently has difficulty finding the device on the network. I have attributed that to possibly spotty wifi coverage where it's located. But another hubitat app that I have used to discover my LG TV is also SSDP based, and for some reason it was very difficult to get that app to detect the TV as well (took quite a few tries, not sure if I did anything differently when it finally did get detected).

I only have one subnet on my LAN. SSDP is based on uPNP, is that right? I usually have uPNP disabled on my Asus router, I tried enabling it, though that doesn't seem to have made a difference.

Happy to try out anything else you can suggest. Thanks again!

**Comment by marktheknife** [comment]
Two other things I was wondering.

I noticed the app repeats the "discovering HEOS devices" every 15 seconds for a few times, and then it says "finished discovery," which also repeats every 15 seconds for a few times. How does it decide to transition from "discovering" to "finished"?

> Is it possible to manually add a device? If I know the HEOS 3 speaker's MAC address for wifi, can I create a virtual device, assign the HEOS speaker driver, save the DNI in a format like what the app gave my Marantz AVR that it discovered and then initialize from the new device's settings page?

edit: Never mind re: question #2, I tried it out and it doesn't do much :)

**Comment by marktheknife** [comment]
Whenever I re-run the discovery, it seems like the "discovering new devices" only goes a total of three times, then "finished" repeats until I click next in the app.

![image](https://user-images.githubusercontent.com/16859844/73281322-cc463900-41bd-11ea-8eac-d6469f9fcb23.png)

**Comment by dcmeglio** [comment]
Yes ssdp is upnp. I can take a look later this week. I can make some tweaks

**Comment by marktheknife** [comment]
Hmm, so I moved the HEOS speaker closer to my wifi access point, and this time it actually did show up in the discovery. Seems to be working now just like the Marantz AVR. I am going to try turning off uPNP on my router and hopefully that won't mess anything up, since I don't have any additional devices to discover.

**Comment by dcmeglio** [comment]
Great! It shouldn’t. Once it’s discovered that shouldn’t be a concern.

**Comment by marktheknife** [comment]
I can confirm that when I enable uPNP on my router, I'm able to discover the HEOS wireless speaker; I decided to delete and re-install the app and devices to test.

However I'm noticing something else now that I have had the speaker and AVR devices in Hubitat. I will open a new issue for that.
